baseURL: "https://itsdrike.com/"
languageCode: "en-us"
title: "ItsDrike"

staticDir: "static/build"
assetDir: "static/build"

theme: ["hugo-notice"]

buildFuture: true
MetaDataFormat: yaml
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
      codeFences: true
      noClasses: false
      style: monokai

summaryLength: 40
enableEmoji: true

enableRobotsTXT: true
rssLimit: 10000

related:
  threshold: 1
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 1
    - name: keywords
      weight: 1
    - name: title
      weight: 1
    - name: subtitle
      weight: 1
